# Exception1.py

def main():
    print("Input no1: ")
    no1 = int(input())
    
    print("Input no2: ")
    no2 = int(input())

    Ans = 0
    Ans = no1 / no2

    print("Division is: ", Ans)

if __name__ == "__main__":
    main()